In [1]:
#assunging feature and variable
#first feature

#using list  for creating file
weather =['sunny','sunny','overcast','Rainy','Rainy','overcast',
          'sunny','sunny','Rainy','sunny','overcast','overcast','Rainy','Rainy']
  #weather and temp indifinte variable
#sunny=2,overcast=1,Rainy=0


In [2]:
#second feature 


temp=['Hot','Hot','Hot','Mild','cool','cool','cool','Mild','cool','Mild',
      'Mild','Mild','Hot','Mild']


#Hot=0 ,Mild=1,Cool=2

In [3]:
#label or target variable
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No',]

#0 means No 1 means Yes

In [4]:
#import lavel Encoder
from sklearn import preprocessing

In [5]:
#creating label Encoder

le=preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)

In [6]:
weather_encoded

array([2, 2, 1, 0, 0, 1, 2, 2, 0, 2, 1, 1, 0, 0], dtype=int64)

In [7]:
#converting string label to number
temp_encoded=le.fit_transform(temp)
label_col=le.fit_transform(play)

In [8]:
temp_encoded

array([0, 0, 0, 1, 2, 2, 2, 1, 2, 1, 1, 1, 0, 1], dtype=int64)

In [9]:
label_col

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [10]:
label_col.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [11]:
#zip function
#combine weather and temparature

features=list(zip(weather_encoded,temp_encoded))


In [12]:
features

[(2, 0),
 (2, 0),
 (1, 0),
 (0, 1),
 (0, 2),
 (1, 2),
 (2, 2),
 (2, 1),
 (0, 2),
 (2, 1),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 1)]

In [13]:
#import KNeighborsClassifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3)

In [15]:
#train the model
model.fit(features,label_col)

KNeighborsClassifier(n_neighbors=3)

In [16]:
#  predict=model.predict([[2,2]])
# sunny=2,overcast=1,Rainy=0

# Hot=0 ,Mild=1,Cool=2

# 0 means No 1 means Yes

In [19]:
n1=int(input('Enter weather feature 1 :'))
n2=int(input('Enter weather  feature 2:'))

Enter weather feature 1 :3
Enter weather  feature 2:5


In [20]:
predict=model.predict([[n1,n2]])

In [21]:
predict

array([0], dtype=int64)

In [22]:
#if you play say Yes or do't play Not
if predict==0:
    print('No')
    
        


else:
    print('Yes')

No
